name: Automated Tests

on: [push]


jobs:
  performance_tests:
    name: performance_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: script.js

